builds:
  - binary: weatherme
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: weatherme
    homepage: https://github.com/eoin-barr/weatherme
    tap:
      owner: eoin-barr
      name: homebrew-eoin-barr
    commit_author:
      name: eoin-barr
      email: eoin.barr@ucdconnect.ie

checksum:
  name_template: "checksums."

env:
  - FOO={{ .Env.OPEN_WEATHER_SECRET }}
  - ENV_WITH_DEFAULT={{ if index .Env "ENV_WITH_DEFAULT"  }}{{ .Env.ENV_WITH_DEFAULT }}{{ else }}default_value{{ end }}
before:
  hooks:
    - go mod tidy
builds:
- binary: program
